export const AuditCategories = {
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  SUPPORT: 'SUPPORT',
  SECURITY: 'SECURITY',
  SETTINGS: 'SETTINGS',
  FINANCE: 'FINANCE',
  MARKETPLACE: 'MARKETPLACE',
  COMMUNICATIONS: 'COMMUNICATIONS',
  SYSTEM: 'SYSTEM',
} as const;

export const AuditActions = {
  // User Management
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_BAN: 'USER_BAN',
  USER_UNBAN: 'USER_UNBAN',
  
  // Support
  TICKET_REPLY: 'TICKET_REPLY',
  TICKET_STATUS_CHANGE: 'TICKET_STATUS_CHANGE',
  TICKET_PRIORITY_CHANGE: 'TICKET_PRIORITY_CHANGE',
  
  // Security
  IP_BAN: 'IP_BAN',
  IP_UNBAN: 'IP_UNBAN',
  
  // Settings
  SETTING_UPDATE: 'SETTING_UPDATE',
  
  // Communications
  ANNOUNCEMENT_CREATE: 'ANNOUNCEMENT_CREATE',
  ANNOUNCEMENT_PUBLISH: 'ANNOUNCEMENT_PUBLISH',
  CAMPAIGN_CREATE: 'CAMPAIGN_CREATE',
  CAMPAIGN_SEND: 'CAMPAIGN_SEND',
  
  // Finance
  COIN_GRANT: 'COIN_GRANT',
  COIN_DEDUCT: 'COIN_DEDUCT',
  
  // Marketplace
  ITEM_APPROVE: 'ITEM_APPROVE',
  ITEM_REJECT: 'ITEM_REJECT',
  
  // System
  EXPORT_DATA: 'EXPORT_DATA',
} as const;

// Map actions to categories
export const actionCategoryMap: Record<string, string> = {
  USER_CREATE: AuditCategories.USER_MANAGEMENT,
  USER_UPDATE: AuditCategories.USER_MANAGEMENT,
  USER_DELETE: AuditCategories.USER_MANAGEMENT,
  USER_BAN: AuditCategories.USER_MANAGEMENT,
  USER_UNBAN: AuditCategories.USER_MANAGEMENT,
  TICKET_REPLY: AuditCategories.SUPPORT,
  TICKET_STATUS_CHANGE: AuditCategories.SUPPORT,
  TICKET_PRIORITY_CHANGE: AuditCategories.SUPPORT,
  IP_BAN: AuditCategories.SECURITY,
  IP_UNBAN: AuditCategories.SECURITY,
  SETTING_UPDATE: AuditCategories.SETTINGS,
  ANNOUNCEMENT_CREATE: AuditCategories.COMMUNICATIONS,
  ANNOUNCEMENT_PUBLISH: AuditCategories.COMMUNICATIONS,
  CAMPAIGN_CREATE: AuditCategories.COMMUNICATIONS,
  CAMPAIGN_SEND: AuditCategories.COMMUNICATIONS,
  COIN_GRANT: AuditCategories.FINANCE,
  COIN_DEDUCT: AuditCategories.FINANCE,
  ITEM_APPROVE: AuditCategories.MARKETPLACE,
  ITEM_REJECT: AuditCategories.MARKETPLACE,
  EXPORT_DATA: AuditCategories.SYSTEM,
};
